/*
The exported Power Query Formula Language (M Language ) can be used with Power Query in Excel
and Power BI Desktop.
For Power BI Desktop follow the instructions below: 
1) Download Power BI Desktop from https://powerbi.microsoft.com/desktop/
2) In Power BI Desktop select: 'Get Data' -> 'Blank Query'->'Advanced Query Editor'
3) Paste the M Language script into the Advanced Query Editor and select 'Done'
*/


let AnalyticsQuery =
let Source = Json.Document(Web.Contents("https://api.loganalytics.io/v1/------/resourceGroups/GR-Erincon/providers/Microsoft.Sql/servers/dbx3/databases/instance1/query", 
[Query=[#"query"="
AzureDiagnostics
| where ResourceProvider == ""MICROSOFT.SQL""
| where TimeGenerated >= ago(60min)
| parse _ResourceId with * ""/microsoft.sql/servers/"" LogicalServerName ""/databases/"" DatabaseName
| summarize Total_count_60mins = sum(delta_waiting_tasks_count_d), Total_duration_60mins = sum(delta_wait_time_ms_d), AVG_waits_per_request = avg(delta_wait_time_ms_d/delta_waiting_tasks_count_d) by LogicalServerName, DatabaseName, wait_type_s

",#"x-ms-app"="AzureFirstPBI",#"scope"="hierarchy",#"prefer"="ai.response-thinning=true"],Timeout=#duration(0,0,4,0)])),
TypeMap = #table(
{ "AnalyticsTypes", "Type" }, 
{ 
{ "string",   Text.Type },
{ "int",      Int32.Type },
{ "long",     Int64.Type },
{ "real",     Double.Type },
{ "timespan", Duration.Type },
{ "datetime", DateTimeZone.Type },
{ "bool",     Logical.Type },
{ "guid",     Text.Type },
{ "dynamic",  Text.Type }
}),
DataTable = Source[tables]{0},
Columns = Table.FromRecords(DataTable[columns]),
ColumnsWithType = Table.Join(Columns, {"type"}, TypeMap , {"AnalyticsTypes"}),
Rows = Table.FromRows(DataTable[rows], Columns[name]), 
Table = Table.TransformColumnTypes(Rows, Table.ToList(ColumnsWithType, (c) => { c{0}, c{3}}))
in
Table
in AnalyticsQuery